SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Password](
	[passwordID] [int] IDENTITY(1,1) NOT NULL,
	[userID] [int] NOT NULL,
	[userPassword] [varchar](max) NOT NULL,
	[passChanged] [datetime] NOT NULL,
 CONSTRAINT [PK_Password] PRIMARY KEY CLUSTERED 
(
	[passwordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Password]  WITH CHECK ADD  CONSTRAINT [FK_Password] FOREIGN KEY([userID])
REFERENCES [dbo].[Users] ([userID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Password] CHECK CONSTRAINT [FK_Password]
GO
